# Mostly modified from https://github.com/nix-community/nur-packages-template/blob/d65ab8218182ba47cd048d50ff1bae0d8b4e7546/.github/workflows/build.yml

labels:
  tier: high

# NOTE: For my machine's network reason, disable this CI
# when:
#   - event: [push, manual]
#     branch: main

matrix:
  NIX_BRANCH:
    - nixpkgs-unstable
    - nixos-unstable
    - nixos-26.05

steps:
  - name: Setup Nix config
    image: docker.io/nixos/nix:2.32.8
    commands:
      - mkdir -p ./.nixconf
      - install -Dm644 /etc/nix/nix.conf ./.nixconf
      - echo "access-tokens = github.com=$${GITHUB_TOKEN}" >> ./.nixconf/nix.conf
      - echo "experimental-features = nix-command flakes" >> ./.nixconf/nix.conf
      - echo "NIX_PATH=https://github.com/NixOS/nixpkgs/archive/refs/heads/${NIX_BRANCH}.tar.gz" >> .envvars
      - echo "NIX_CONF_DIR=$(realpath ./.nixconf)" >> .envvars
    environment:
      GITHUB_TOKEN:
        from_secret: github_token

  - name: Show nixpkgs version
    image: docker.io/nixos/nix:2.32.8
    commands:
      - source ./.envvars
      - nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version'

  - name: Check evaluation
    image: docker.io/nixos/nix:2.32.8
    commands:
      - source ./.envvars
      - |
        nix-env -f . -qa \* --meta --xml \
          --allowed-uris https://static.rust-lang.org \
          --option restrict-eval true \
          --option allow-import-from-derivation true \
          --drv-path --show-trace \
          -I nixpkgs=$(nix-instantiate --find-file nixpkgs) \
          -I $PWD

  - name: Build nix packages
    image: docker.io/nixos/nix:2.32.8
    commands:
      - source ./.envvars
      - nix shell -f '<nixpkgs>' nix-build-uncached -c nix-build-uncached ci.nix -A cacheOutputs
